; ============================================================
;  PlatformIO configuration
;  Board  : Waveshare ESP32-S3-Touch-AMOLED-1.64
; ============================================================

[env:waveshare_amoled_1_64]
; https://forum.elecrow.com/discussion/1190/beware-of-the-3-2-0-esp-board-package
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board     = esp32-s3-devkitc-1    ; closest stock board – overrides below
framework = arduino

; ── Flash / PSRAM ──────────────────────────────────────────
board_build.arduino.memory_type = qio_opi   ; OPI PSRAM (8 MB)
board_build.f_flash             = 80000000L
board_build.flash_mode          = qio
board_upload.flash_size         = 16MB

; ── CPU / USB ──────────────────────────────────────────────
board_build.f_cpu               = 240000000L
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1          ; HWCDC via native USB
    -DARDUINO_USB_CDC_ON_BOOT=1   ; Serial → USB-CDC at boot

    ; ── LVGL feature flags ─────────────────────────────────
    -DLV_CONF_INCLUDE_SIMPLE      ; pick up lv_conf.h from include/
    -I include                    ; folder where lv_conf.h lives

    ; ── Display geometry ───────────────────────────────────
    -DLCD_WIDTH=280
    -DLCD_HEIGHT=456


monitor_speed = 115200

lib_deps =
    ; Arduino-GFX – CO5300 QSPI driver lives here
    moononournation/GFX Library for Arduino @ ^1.4.9
    ; LVGL 8 – stable, widely supported
    lvgl/lvgl @ ~8.3.11
    adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit BNO055@^1.6.4
